name: sol_connect
description: A timetable for self-organized learning with a phase plan
publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  awesome_dialog: ^2.1.2
  cupertino_icons: ^1.0.2
  excel: 2.0.0-null-safety-3
  file_picker: ^4.3.1
  flutter:
    sdk: flutter
  flutter_search_bar: ^3.0.0-dev.1
  flutter_secure_storage: ^5.0.2
  flutter_staggered_animations: ^1.0.0
  fluttericon: ^2.0.0
  google_fonts: 2.2.0
  hooks_riverpod: ^1.0.3
  http: ^0.13.4
  intl: ^0.17.0
  liquid_pull_to_refresh: ^3.0.1
  logger: ^1.1.0
  shared_preferences: ^2.0.11
  url_launcher: ^6.0.18

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - "assets/demo/timetables/"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
